#!/bin/sh
uci batch <<-EOF
	set luci.themes.Piraten=/luci-static/piraten
	set luci.main.mediaurlbase=/luci-static/piraten
        commit luci
	set freifunk.upgrade.repository=http://dev.dd19.de/~alx/piraten
	commit freifunk
EOF
	
