#!/bin/sh
# versioncheck stolen from remote_update
local D2='\([0-9]\{2\}\)'                                           
local D4='\([0-9]\{4\}\)'                                           
local NL='
'
find_local_version()
{
        if [ -f /rom/etc/banner ]; then
                sed -ne "s!.*$D4/$D2/$D2 $D2:$D2.*!\\1\\2\\3\\4\\5!p;t" \
                        /rom/etc/banner
        else
                date +"%Y%m%d%H%M" -r /bin/sh
        fi
}

server=`uci get system.@pirate[0].heartbeatserver`
node_id=`uci get system.@system[0].nodeid`
hostname=`uci get system.@system[0].hostname`
version=`find_local_version`
lat=`uci show olsrd|grep .lat=|cut -d = -f2`
lon=`uci show olsrd|grep .lon=|cut -d = -f2`
crew=seetiger
lv=berlin
wget -s "$server?node_id=$node_id&name=$hostname&lat=$lat&lon=$lon&rev=$version&crew=$crew&lv=$lv"

#missing:
# crew:string
# lv:string
# check whether there are values, otherwise omit
# partei:integer //should be 1, if pirate party node
# checkbox needed
 
# neighboors:integer
# clients:integer
 
