#!/bin/sh
# versioncheck stolen from remote_update
local D2='\([0-9]\{2\}\)'                                           
local D4='\([0-9]\{4\}\)'                                           
local NL='
'
find_local_version()
{
        if [ -f /rom/etc/banner ]; then
                sed -ne "s!.*$D4/$D2/$D2 $D2:$D2.*!\\1\\2\\3\\4\\5!p;t" \
                        /rom/etc/banner
        else
                date +"%Y%m%d%H%M" -r /bin/sh
        fi
}
#TODO: check mode {update,information, highscore}

server=`uci get system.@pirate[0].heartbeatserver`
node_id=`uci get system.@system[0].nodeid`
hostname=`uci get system.@system[0].hostname`
version=`find_local_version`
lat=`uci show olsrd|grep .lat=|cut -d = -f2`
lon=`uci show olsrd|grep .lon=|cut -d = -f2`
crew=`uci get freifunk.contact.crew`
lv=`uci get freifunk.contact.landesverband`
#based on reachable adhoc networks
neighboors=`expr $(iwlist wl0 scanning|grep -i adhoc|wc -l) - 1`

#TODO this only submit the current connected clients
# we need a routine, which constantly record the clients for 24h hours
clients=`cat /tmp/dhcp.leases|wc -l`

#if mode == update
#wget -s "$server?node_id=$node_id&rev=$version"

#if mode == information
#wget -s "$server?node_id=$node_id&name=$hostname&lat=$lat&lon=$lon&rev=$version&crew=$crew&lv=$lv"

#if mode == highscore
wget -s "$server?node_id=$node_id&name=$hostname&lat=$lat&lon=$lon&rev=$version&crew=$crew&lv=$lv&neighboors=$neighboors&clients=$clients"

#missing:
# crew:string
# lv:string
# partei:integer //should be not set if pirate party germany
# land:string //should be not set if germany
 
# neighboors:integer
# clients:integer
 
